language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t vubaoanhdung/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vubaoanhdung/react-test npm test

after_success:
    - docker build -t vubaoanhdung/multi-client ./client
    - docker build -t vubaoanhdung/multi-nginx ./nginx
    - docker build -t vubaoanhdung/multi-server ./server
    - docker build -t vubaoanhdung/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Takes those images and push them to docker hub
    - docker push vubaoanhdung/multi-client
    - docker push vubaoanhdung/multi-nginx
    - docker push vubaoanhdung/multi-server
    - docker push vubaoanhdung/multi-worker
